### ISSUE TITLE
removeAttr('onclick') not working in IE

### ISSUE THREAD

**Issue by fmagron** [Ifnot/PopConfirm#20]
For hard onclick attribute the current code for removing onclick is not working in IE, resulting in onclick being triggered before the popup appears.

Instead of 
$(self).removeAttr('onclick');

Use
$(self).prop("onclick", null);

See advice in https://api.jquery.com/removeAttr/

Cheers
Franck

**Comment by Ifnot** [comment]
Thanks, this is fixed on 623515d1c7e4a344cd6e271ce3eefa800c255958

Release : v0.4.3
