### ISSUE TITLE
Button name/value not included in submitted form

### ISSUE THREAD

**Issue by kaetemi** [Ifnot/PopConfirm#21]
Fixed by adding following before form.submit() call:

<pre>
            var hidden = document.createElement('input');
            hidden.type = 'hidden';
            hidden.name = self.attr('name');
            hidden.value = self.attr('value');
            form.append(hidden);
</pre>

**Comment by Ifnot** [comment]
Hi kaetemi !

It is Interesting as the submit button is not submit, however i think we have to check if there are attr name/value present on the button.

Would you PR your fix ?

Thanks :)

**Comment by Ifnot** [comment]
WIth dd3a278 i created 9f5c503609a1898418925f069f4bef06c2758f54. I fixed this.
