### ISSUE TITLE
Allow specifying of handlers for onConfirmation.

### ISSUE THREAD

**Issue by ivanoronee** [Ifnot/PopConfirm#29]
It would be nice to allow specifying of handlers for onConfirm.
Case in point, i would like to proceed with executing some javascript if the user allows the operation to continue. 

I cannot currently do this because all the onclick events associated with the object are removed by the plugin. 

What would be cool would be providing a mechanism for providing handlers for onConfirm.

**Comment by Ifnot** [comment]
Interesting behaviour proposal.

Guys, please +1 this feature if you are interested.

**Comment by RamonZayas** [comment]
Hi there... I currently have this:

```html
<a  class="trash-key"
  href="#"
  data-post-url="...some url ... "
  data-confirm-title="Are you sure?"
  data-confirm-content="About to delete key <strong>{{$key}}</strong> from database."
  data-confirm-placement="top"
  data-confirm-container="body"
  data-confirm-yesBtn="Ok, delete!"
  data-confirm-noBtn="No"
  > <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
</a>
```
```javascript
$('a.trash-key').click(function (e){
  var row = $(this).closest('tr');
  var url = $(this).data('post-url');
  var id = row.attr('id');
  $.post( url, {id: id}, function(){
    row.remove();
    } );
    return false;
});

$("a.trash-key").popConfirm();
```

The javascript is executed ONLY if I click the yesBtn.

**Comment by Ifnot** [comment]
@RamonZayas this behaviour is normal, this it the main goal of the plugin : to queue an action of a button and execute it with a confirmation on the YES button.

**Comment by RamonZayas** [comment]
I know, but that is exactly what @ivanoronee is asking for... am I right?... or is this something completely different? what am I missing?.

**Comment by Ifnot** [comment]
I thinks it is different.

Can you explain your case with more precision ?

**Comment by enekogb** [comment]
Isn't this solved with #33?

**Comment by Ifnot** [comment]
This plugin is an "Simple action confirmation plugin".

So, it ask a confirmation before doing an action, and do the action only if we click yes.

@enekogb : do you think the "action confirmation" is too ambigous ? Should i add a example ? (like a confirm() in javascript ?)

**Comment by enekogb** [comment]
@Ifnot When i read the doc the first time, it wasn't clear to me, maybe because i had used @tavicu [bs-confirmation](https://github.com/tavicu/bs-confirmation), which has an _onConfirm_ callback.

I realized how this plugin works, when I checked the fiddle demo.

Maybe a little change in README.md like #34 whould make it clearer.

**Comment by Ifnot** [comment]
I have merged the example.

I need some docs update as the action can be manual.

I will work on it when i have the time :)
