### ISSUE TITLE
Example on http://jsfiddle.net/RDh7E/28/ not working

### ISSUE THREAD

**Issue by ppazos** [Ifnot/PopConfirm#31]

**Comment by Ifnot** [comment]
Working well here, what is the problem ?

**Comment by ppazos** [comment]
I think comes from JS

https://rawgithub.com/ifnot/PopConfirm/master/jquery.popconfirm.js
Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
fiddle.jshell.net/:60 Uncaught TypeError: $(...).popConfirm is not a function
(index):60 Uncaught TypeError: $(...).popConfirm is not a function

**Comment by Ifnot** [comment]
Strange, i do not have this problem here :(

**Comment by ppazos** [comment]
Sorry, dismiss this, ERR_SSL_VERSION_OR_CIPHER_MISMATCH is an issue with Chrome on old windows machines, works fine on FF.
