### ISSUE TITLE
PopConfirm doesn't work with Bootstrap 4 and jQuery 3.3.1

### ISSUE THREAD

**Issue by bhall7** [Ifnot/PopConfirm#41]
PopConfirm is currently not working properly in Bootstrap 4 and jQuery 3.3.1. For example, when trying to employ PopConfirm to confirm a form submission, the form does not submit and the result is an un-closable instance of the popover that only goes away when the DOM is refreshed. I'd fix it but I don't know how, and I suspect that it may be due to a change in jQuery. 

The Bootstrap 4 changes are easy enough because I think it's mostly just changes to the button names and styling. But, the bigger question is getting forms to submit and removing the popover instance after it is submitted.

**Comment by johnabela** [comment]
I am using:

- jQuery: 3.3.1
- Bootstrap: 4.1.3
- PopConfirm: 0.4.5

My loading order is:

1. bootstrap.min.css
2. jquery.min.js
3. bootstrap.min.js
4. jquery.popconfirm.js

All is working for me.

**Comment by bhall7** [comment]
Thanks @johnabela for the reply. Hmm, curious that it's working for you. I'll have to do some more fiddling and see if I can share the issue I'm seeing.

**Comment by bhall7** [comment]
I had to modify jquery.popconfirm.js to reflect the accurate button styling, but eventually got it to work with jQuery 3.3.1 and Bootstrap 4.1.3.

**Comment by IfnotFr** [comment]
Can you share with us the modifications you made to improve the package ? :)

**Comment by johnabela** [comment]
@Ifnot - Here is what I did...

Inside the `popConfirm: function (options) {` I added a new variable/option, after `noBtn:'No',` called `btnColor: 'btn-success'` this allows us/me to pass through any different btn color option that bootstrap offers.

Next, within `self.popover()` the `content` variable goes from:

`content: options.content + '<p class="button-group" style="margin-top: 10px; text-align: center;"><button type="button" class="btn btn-small confirm-dialog-btn-abort">' + options.noBtn + '</button> <button type="button" class="btn btn-small btn-danger confirm-dialog-btn-confirm">' + options.yesBtn + '</button></p>'`

to:

`content: options.content + '<p class="button-group" style="margin-top: 10px; text-align: center;"><button type="button" class="btn btn-small confirm-dialog-btn-abort">' + options.noBtn + '</button> <button type="button" class="btn btn-small ' + options.btnColor + ' confirm-dialog-btn-confirm">' + options.yesBtn + '</button></p>'`

Those are the only changes that I have made.

**Usage:**

`$("[data-toggle='popConfirmation']").popConfirm({title:"Please Confirm!",content:"Final warning&hellip;",placement:"top",container:"body",yesBtn:"Confirm",noBtn:"Cancel",btnColor:"btn-danger"});`

**Comment by bhall7** [comment]
I changed the styling on the buttons to suit my preferences on line 119 to match the new button names in Bootstrap 4. Also, on line 153, I changed `.confirm-dialog-btn-abord` to `.confirm-dialog-btn-abort`

**Comment by bhall7** [comment]
@johnabela, does PopConfirm work for you when confirming an action within a modal?

**Comment by johnabela** [comment]
@bhall7  - ugh, do I ever hate bootstrap modals. I avoid them like the plague. But, that said, yep, my updated version _(call it, 0.4.6, if you want too)_ does work with the latest bootstrap/jquery/modal.

Here is a [JSFiddle showing it works](https://jsfiddle.net/abela/aq9Laaew/292808/). With the exception of the button that has the `id="popConfirmation"`  _(html line # 17, I think)_ this is code taken directly from the bootstrap website.

I confirmed it worked in Chrome and Firefox, did not test anything else.

**Comment by bhall7** [comment]
I'm still having issues getting PopConfirm to work for me. On the site I'm working on, the buttons are not appearing:
<img width="291" alt="popconfirm_no buttons" src="https://user-images.githubusercontent.com/513487/53046954-7f56d000-344e-11e9-92d8-5433df5ac27a.png">

~~However, I'm unable to replicate the issue on Codeply~~. I recreated the issue on this Codeply: https://www.codeply.com/go/2BWcRgi8mc I'm now using the following dependencies and updated versions, loading them in the following order:

- Bootstrap CSS 4.3.1
- jQuery 3.3.1
- popper.js 1.14.7
- Bootstrap 4.3.1
- [PopConfirm 0.4.5](https://raw.githubusercontent.com/Ifnot/PopConfirm/master/jquery.popconfirm.js)

I'm using the following settings for my confirm button, and I can trigger it, but now I don't get any buttons. When I change the placement setting, it reflects the settings properly, I just can't figure out why the buttons are not there:
```
    $(".btn-delete").popConfirm({
        title: "Delete Item",
        content: "Are you sure you want to delete this item?",
        placement: "top",
        container: false
    });
```
When I click on the element in Chrome Dev Tools, it simply doesn't show the buttons at all:
<img width="564" alt="no pop confirm buttons" src="https://user-images.githubusercontent.com/513487/53047494-c6919080-344f-11e9-8015-513467433bc8.png">

There are no errors showing up in the console, either.

Any suggestions would be greatly helpful!

**Comment by bhall7** [comment]
**UPDATE:** The invisible buttons issue appears to be a new issue introduced with [Bootstrap 4.3.1](https://github.com/twbs/bootstrap/releases/tag/v4.3.1), which addressed some XSS issues. When I revert back to Boostratp 4.2.1, the buttons show up just fine:
<img width="281" alt="popconfirm_buttons" src="https://user-images.githubusercontent.com/513487/53050299-3e62b980-3456-11e9-897f-12bcb902c77c.png">

I recreated the issue in this Codeply: https://www.codeply.com/go/2BWcRgi8mc

**Comment by bhall7** [comment]
In Bootstrap 4.3.1, they introduced a sanitizer for Tooltips and Popovers (https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer). To allow buttons and get PopConfirm to work, you need to add the following line to your JavaScript file to whitelist buttons:
  `$.fn.tooltip.Constructor.Default.whiteList.button = []`
I updated the [Codeply](https://www.codeply.com/go/2BWcRgi8mc) showing this working. Here's a link to the StackOverflow answer: https://stackoverflow.com/questions/54854862/bootstrap-4-3-1-broke-popconfirm/54942434#54942434.
